import type { AppState } from '../types/core'

export const initialState: AppState = {
  spectra: [],
  activeSpectrumId: undefined,
  plot: {
    showGrid: true,
    showAllSpectra: false,
    stackOffset: 0,
    xMin: null,
    xMax: null,
    yMin: null,
    yMax: null,
    invertX: false,
  },
  processedYById: {},
  baselineYById: {},
  smoothedYById: {},
  baseline: {
    enabled: false,
    lambda: 1e6,
    p: 0.01,
    iterations: 10,
  },
  smoothing: {
    window: 11,
    polyOrder: 3,
  },
  graphics: {
    xLabel: 'X',
    yLabel: 'Y',
    showXTickLabels: true,
    showYTickLabels: true,
    showGrid: true,
    gridColor: '#e2e8f0',
    gridWidth: 1,
    previewCanvasSize: false,
    axisLineWidth: 2,
    axisLineColor: '#94a3b8',
    frameMode: 'open',
    traceLineWidth: 2,
    fontFamily: 'Arial',
    baseFontSize: 16,
    tickFontSize: 12,
    palette: 'auto',
    inlineSpectrumLabels: false,
    exportWidth: 1600,
    exportHeight: 900,
  },
}
