import type { AppState } from '../types/core'

export const initialState: AppState = {
  spectra: [],
  activeSpectrumId: undefined,
  plot: {
    showGrid: true,
    showAllSpectra: false,
    stackOffset: 0,
    xMin: null,
    xMax: null,
    yMin: null,
    yMax: null,
    invertX: false,
  },
  processedYById: {},
  baselineYById: {},
  smoothedYById: {},
  baseline: {
    enabled: false,
    showOverlay: true,
    lambda: 1e6,
    p: 0.01,
    iterations: 10,
  },
  smoothing: {
    window: 11,
    polyOrder: 3,
  },
  graphics: {
    xLabel: 'X',
    yLabel: 'Y',
    axisLineWidth: 4,
    traceLineWidth: 4,
    fontFamily: 'Arial',
    baseFontSize: 32,
    tickFontSize: 30,
    palette: 'auto',
    exportWidth: 1600,
    exportHeight: 900,
    showXTickLabels: true,
    showYTickLabels: false,
    axisLineColor: '#000000',
    frameMode: 'open',
    showGrid: false,
    gridColor: '#e2e8f0',
    gridWidth: 1,
    inlineSpectrumLabels: true,
    previewCanvasSize: false,
  },
}
